module.exports = {
  ID_Estudiante: String,
  nombre: String,
  Apellido_Estudiante: String,
  Sexo: String,
  Fecha_Nacimiento: Date,
  Nacionalidad: String,
  Pasaporte: String,
  NIT: String,
  NUP: String,
  Direccion: String,
  emailaddress: String,
  Departamento: String,
  Municipio: String,
  Telefono_Casa: String,
  Telefono_Celular: String,
  Red_Social: String,
};
